---
- name: Adicionar repositório Helm do Harbor
  kubernetes.core.helm_repository:
    name: harbor
    repo_url: https://helm.goharbor.io

- name: Criar namespace {{ harbor_namespace }}
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ harbor_namespace }}"

- name: Senha do admin do Harbor (Bitwarden)
  include_role:
    name: credentials
    tasks_from: initial_password
  vars:
    initial_password_secret: harbor-admin
    initial_password_namespace: "{{ harbor_namespace }}"
    initial_password_data:
      HARBOR_ADMIN_PASSWORD: !unsafe "{{ .password }}"

- name: Instalar/Atualizar Harbor
  kubernetes.core.helm:
    name: harbor
    chart_ref: harbor/harbor
    chart_version: "{{ harbor_chart_version | default(omit, true) }}"
    release_namespace: "{{ harbor_namespace }}"
    create_namespace: true
    update_repo_cache: true
    wait: true
    wait_timeout: 10m
    values: "{{ lookup('template', 'values.yml.j2') | from_yaml }}"
