---
- name: Adicionar repositório Helm do ArgoCD
  kubernetes.core.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm

- name: Instalar/Atualizar ArgoCD
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    release_namespace: "{{ argocd_namespace }}"
    create_namespace: true
    update_repo_cache: true
    wait: true
    wait_timeout: 5m
