---
- import_tasks: bitwarden.yml

- name: Validar variáveis obrigatórias
  assert:
    that:
      - github_org | length > 0
      - github_user | length > 0
      - github_token | length > 0
      - bitwarden_access_token | length > 0
      - bitwarden_organization_id | length > 0
      - bitwarden_project_id | length > 0
    fail_msg: >-
      Faltam variáveis. Preencha github_org, github_user, bitwarden_organization_id
      e bitwarden_project_id em roles/argocd/defaults/main.yml.
    quiet: true
  no_log: true

- import_tasks: prereqs.yml
- import_tasks: argocd.yml
- import_tasks: image_updater.yml
- import_tasks: external_secrets.yml
- import_tasks: applicationset.yml
- import_tasks: credentials.yml
