---
- name: Adicionar repositório Helm do Jenkins
  kubernetes.core.helm_repository:
    name: jenkins
    repo_url: https://charts.jenkins.io

- name: Instalar/Atualizar Jenkins
  kubernetes.core.helm:
    name: jenkins
    chart_ref: jenkins/jenkins
    chart_version: "{{ jenkins_chart_version | default(omit, true) }}"
    release_namespace: "{{ jenkins_namespace }}"
    create_namespace: true
    update_repo_cache: true
    wait: true
    wait_timeout: 10m
    values_files:
      - "{{ role_path }}/files/values.yml"
